### ISSUE TITLE
Image url nevraci obrazky dobre

### ISSUE THREAD

**Issue by proxycz** [MarhyCZ/ivysilani_tvOS#1]
Ahoj v web/app/lib/template-helpers.js radek 37 mas navic 'http:' String. Obrazky to pak nenacte dobre. Kdyz to smaznes tak se obrazky loadi krasne :]

**Comment by MarhyCZ** [comment]
Tak mi to zase změnili zpátky :D Před týdnem jsem to tam přidával, protože ty linky začaly být ve tvaru. //imgct/...

Díky, opravím to :]

**Comment by proxycz** [comment]
Hele muzu si to u sebe upravit a pridat si tam prave sleduji a tak?

**Comment by MarhyCZ** [comment]
Určitě! :) Klidně to pak zpátky přidám ke mně.
