### ISSUE TITLE
newbie question - how to fix compilation issues?

### ISSUE THREAD

**Issue by oplatek** [MarhyCZ/ivysilani_tvOS#10]
Hi!

Thank you for the app. It looks really promising.
I am a newbie in XCode/tvOS development.

Can you please explain me how can I bypass the following signing issues?

<img width="960" alt="Screenshot 2020-06-14 at 20 32 08" src="https://user-images.githubusercontent.com/229266/84601133-6f9e9e80-ae7e-11ea-99fa-3d3424ef55e4.png">

Thank you!

**Comment by martinhanes** [comment]
Hi, you need to sign to your apple id to be able to provide some provisioning profile. Without one, you can’t deploy app to your local device.

M.

**Comment by oplatek** [comment]
Thanks @martinhanes ! Worked like a charm. Great app!

For future reference what I did:
1. Open Preferences in XCode / Accounts and added Apple ID account
2. Right clicked on the iVysilani project and opened properties, switched to Signing & Capabilities tab, selected MY_OWN (Personal Team), entered the identifier iVysilani-recompiled and kept "Automatic manage signing"

PS: I am not sure, but I think it was for me necessary to
 sign in to free developer program with my Apple ID at https://help.apple.com/developer-account/#/dev2b5e6d209 in order to be able to step 2.

**Comment by martinhanes** [comment]
Perfect :-) Glad it helped. 

Signing to dev program seems like mandatory step, as you pointed out. There’s also different “provisioning period” of free accounts than on paid ones :-/

https://stackoverflow.com/questions/36998956/why-does-my-free-xcode-provisioning-profile-only-last-7-days <https://stackoverflow.com/questions/36998956/why-does-my-free-xcode-provisioning-profile-only-last-7-days>

M.
